AbcSize:
  Enabled: false
AndOr:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
ClassAndModuleCamelCase:
  Enabled: false
ClassLength:
  Enabled: false
CommentAnnotation:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
Encoding:
  Enabled: false
Eval:
  Enabled: false
Style/FileName:
  Exclude:
    - bin/ffi-yajl-bench
FormatString:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ModuleLength:
  Enabled: false
PerceivedComplexity:
  Enabled: false
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%q': '{}'
    '%Q': '{}'
    '%w': '{}'
    '%W': '{}'
    '%x': '{}'
RegexpLiteral:
  Enabled: false
Style/Semicolon:
  Enabled: false
SignalException:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
SpaceInsideBrackets:
  Enabled: false
SpaceInsideParens:
  Enabled: false
StringLiterals:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
UnusedMethodArgument:
  Enabled: false
UnusedBlockArgument:
  Enabled: false
